# Google OAuth
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""

# MongoDB
MONGODB_URI = "127.0.0.1"
MONGODB_PORT = 27017
MONGODB_DB = "university_courses"
MONGODB_COLLECTION_FOLDERS = "folders"
MONGODB_COLLECTION_USERS = "users"
MONGODB_COLLECTION_SUBSCRIPTIONS = "subscriptions"
MONGODB_COLLECTION_LOGS = "logs"
MONGODB_COLLECTION_FOLDER_CHANGES = "folder_changes"
